# Generated by Django 2.0 on 2020-08-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='e_status',
            field=models.CharField(default='not verified', max_length=50),
        ),
    ]
