# Generated by Django 2.0 on 2020-08-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200811_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='name',
            new_name='fname',
        ),
    ]
