# Generated by Django 2.0 on 2020-08-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20200818_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='typ',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='identity',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
