# Generated by Django 2.0 on 2020-08-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200818_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='onetimepassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=50)),
            ],
        ),
    ]
