# Generated by Django 2.0 on 2020-08-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='u',
            field=models.ForeignKey(null=True, on_delete='DO_NOTHING', to='registration.user_data'),
        ),
    ]
