# Generated by Django 2.0 on 2020-08-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20200819_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='u',
        ),
        migrations.AddField(
            model_name='user_data',
            name='otp',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='onetimepassword',
        ),
    ]
