# Generated by Django 2.0 on 2020-08-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20200820_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingridients',
            name='image',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
