# Generated by Django 2.0 on 2020-08-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_ingridients_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_num', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='order',
            field=models.ForeignKey(on_delete='DO_NOTHING', to='shopping.order'),
        ),
    ]
